version: "3.8"
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - .env.production
    restart: unless-stopped
    volumes:
      - ./temp:/usr/src/app/temp
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
