version: "3.8"
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    network_mode: "host"
    env_file:
      - .env.production
    restart: unless-stopped
    volumes:
      - ./temp:/usr/src/app/temp
    depends_on:
      - redis
    environment:
      - REDIS_HOST=localhost
      - REDIS_PORT=6379
      - BREVO_SMTP_USER=${BREVO_SMTP_USER}
      - BREVO_SMTP_KEY=${BREVO_SMTP_KEY}
      - EMAIL_USER=${EMAIL_USER}

  redis:
    image: redis:6.2-alpine
    restart: always
    network_mode: "host"
    command: redis-server --save 20 1 --loglevel warning
    volumes:
      - redis_data:/data

volumes:
  redis_data:
    driver: local
