version: "3.8"
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    network_mode: "host"  # Ubah ke network mode host
    env_file:
      - .env.production
    restart: unless-stopped
    volumes:
      - ./temp:/usr/src/app/temp
    depends_on:
      - redis
    environment:
      - REDIS_HOST=localhost  # Ubah karena menggunakan network host
      - REDIS_PORT=6379
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.route_localnet=1

  redis:
    image: redis:6.2-alpine
    restart: always
    network_mode: "host"  # Ubah ke network mode host
    command: redis-server --save 20 1 --loglevel warning
    volumes:
      - redis_data:/data

volumes:
  redis_data:
    driver: local